"""
配置模块
"""

from .settings import Settings
from .constants import (
    QUEUE_KEY,
    TASK_SET_KEY,
    CONNECTION_PREFIXES,
    NODE_TYPE_KEYWORDS,
    HARDWARE_KEYWORDS,
    NODE_TYPE_ALLSTARLINK,
    NODE_TYPE_OTHERS,
    NODE_RANK_UNKNOWN,
    NODE_RANK_HUB,
    NODE_RANK_REPEATER
)

__all__ = [
    'Settings',
    'QUEUE_KEY',
    'TASK_SET_KEY',
    'CONNECTION_PREFIXES',
    'NODE_TYPE_KEYWORDS',
    'HARDWARE_KEYWORDS',
    'NODE_TYPE_ALLSTARLINK',
    'NODE_TYPE_OTHERS',
    'NODE_RANK_UNKNOWN',
    'NODE_RANK_HUB',
    'NODE_RANK_REPEATER'
]
